apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: jenkins-storage
  local:
    path: /opt/jenkins_home
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jenkins-storage
  namespace: kube-ops
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jenkins-home
  name: jenkins-home-data
  namespace: kube-ops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: jenkins-storage
  resources:
    requests:
      storage: 20Gi