apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "slave"
    app: "jenkins_home"
  namespace: "kube-ops"
spec:
  serviceAccountName: "jenkins"
  containers:
    - name: "jnlp"
      image: "jenkins/inbound-agent:alpine3.20-jdk21"
      workingDir: "/home/jenkins/agent"
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace"
    - name: "docker"
      image: "docker:27.3.1-dind-alpine3.20"
      workingDir: "/home/jenkins/agent"
      volumeMounts:
        - name: "workspace"
          mountPath: "/home/jenkins/agent"
        - name: "docker-config"
          mountPath: "/etc/docker/daemon.json"
          subPath: "daemon.json"
        - name: "docker-config"
          mountPath: "/etc/docker/build_kit.toml"
          subPath: "build_kit.toml"
      securityContext:
        privileged: true
  volumes:
    - name: "workspace"
      persistentVolumeClaim:
        claimName: "jenkins-home-data"
    # 设置docker-daemon-config的配置，如果没有则不需要，如果有请在configmap.yaml配置
    - name: "docker-config"
      configMap:
        name: "docker-daemon-config"
