# 第一阶段：构建应用
FROM --platform=${BUILDPLATFORM} golang:1.23.6 AS builder
WORKDIR /app
ENV GOPROXY=https://goproxy.io,direct
COPY . /app

# 编译适用于所有架构的二进制文件
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o http-test-amd64 .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o http-test-arm64 .

# 第二阶段：为不同平台复制构建文件
FROM alpine:3.21.2
WORKDIR /app
ARG TARGETARCH
COPY --from=builder /app/http-test-${TARGETARCH} ./http-test
EXPOSE 8080
CMD ["./http-test"]
