apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -beijing
namespace: beijing

resources:
- ../../base

patches:
- path: resources.yaml
- path: service.yaml

replicas:
- count: 3
  name: gin-http

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    zone: beijing

images:
- name: images
  newName: harbor.dyness.cn/backend/http-main
  newTag: ec206e8-1729848710
