apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml

labels:
  - pairs:
      app: gin-http
    includeSelectors: true
    includeTemplates: true

replicas:
- count: 2
  name: gin-http